version: 2

sources:
  - name: Demo_dev
    database: dbt-project-trainning-setup
    schema: dbt_Demo
    tables:
      - name: dados_transacionais
      - name: dim_data
      - name: hierarquia_cliente
  - name: Demo_prod
    database: dbt-project-trainning-setup
    schema: dbt_Demo_production
    tables:
      - name: dados_transacionais
      - name: dim_data
      - name: hierarquia_cliente